// gen-places.mjs - build text/en_us/PlaceText.xml from the name pools: node devtools/gen-places.mjs [--check] [--tsv <file>]
//
// Every place name the labels can draw gets two tags: LOC_GEO_PLACE_<NAME>, the bare name (what the National Park
// mod names a park after), and LOC_GEO_NAME_<TYPE>_<NAME>, the whole label for that kind of place, so a language
// can word "Isle of Sicilia" or "Adriatic Sea" its own way. The English is the text the labels drew before they were
// translated: the pool name, framed by frame(). --check exits 1 when the file is out of date with the pools.
// --tsv writes a table for translators: tag, English, kind, type, and the civilizations whose pools hold the name.
import fs from "node:fs";
import { CIV_NAMES, GENERIC } from "../ui/geo-labels-toponyms.js";
import { frame } from "../ui/geo-labels-format.js";
import { nameTag, placeTag } from "../ui/geo-labels-l10n.js";

const OUT = "text/en_us/PlaceText.xml";
const esc = (s) => String(s).replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;");

const places = new Map(); // tag -> { name, civs:Set }
const labels = new Map(); // tag -> { name, type, civs:Set }
function add(type, name, civ) {
  const p = placeTag(name);
  if (!places.has(p)) places.set(p, { name, civs: new Set() });
  places.get(p).civs.add(civ);
  const n = nameTag(type, name);
  if (!labels.has(n)) labels.set(n, { name, type, civs: new Set() });
  labels.get(n).civs.add(civ);
}
for (const [civ, pools] of Object.entries(CIV_NAMES)) {
  for (const [type, names] of Object.entries(pools)) for (const n of names) add(type, n, civ.replace(/^CIVILIZATION_/, ""));
}
for (const [type, names] of Object.entries(GENERIC)) for (const n of names) add(type, n, "(neutral)");

const sorted = (m) => [...m.entries()].sort((a, b) => a[0].localeCompare(b[0]));
const lines = [
  '<?xml version="1.0" encoding="utf-8"?>',
  "<!-- Generated by devtools/gen-places.mjs from ui/geo-labels-toponyms.js; edit the pools and rerun. -->",
  "<Database>",
  "    <EnglishText>",
  "        <!-- Bare place names. -->",
  ...sorted(places).map(([tag, v]) => `        <Row Tag="${tag}"><Text>${esc(v.name)}</Text></Row>`),
  "        <!-- Whole labels, one per kind of place a name is drawn on. -->",
  ...sorted(labels).map(([tag, v]) => `        <Row Tag="${tag}"><Text>${esc(frame(v.type, v.name))}</Text></Row>`),
  "    </EnglishText>",
  "</Database>",
  "",
];
const xml = lines.join("\n");

const args = process.argv.slice(2);
const tsvAt = args.indexOf("--tsv");
if (tsvAt >= 0) {
  const rows = ["tag\tenglish\tkind\ttype\tcivs"];
  for (const [tag, v] of sorted(places)) rows.push([tag, v.name, "place", "", [...v.civs].join(",")].join("\t"));
  for (const [tag, v] of sorted(labels)) rows.push([tag, frame(v.type, v.name), "label", v.type, [...v.civs].join(",")].join("\t"));
  fs.writeFileSync(args[tsvAt + 1], rows.join("\n") + "\n");
}
if (args.includes("--check")) {
  const now = fs.existsSync(OUT) ? fs.readFileSync(OUT, "utf8") : "";
  if (now !== xml) { console.error(`${OUT} is out of date; run node devtools/gen-places.mjs`); process.exit(1); }
  console.log(`${OUT}: up to date (${places.size} places, ${labels.size} labels)`);
} else {
  fs.writeFileSync(OUT, xml);
  console.log(`wrote ${OUT}: ${places.size} places, ${labels.size} labels`);
}
